#!/bin/sh /etc/rc.common

START=21
STOP=90
USE_PROCD=1

CONF="/etc/EAP/wpa_supplicant.conf"

start_service(){
  # set -x
  PROC=/usr/sbin/wpa_supplicant
  INET=br-wan
  ARGS="-dd -D wired -i ${INET} -c ${CONF}"
  
  # wait for interface
  until [ -e /sys/class/net/${INET} ]
  do
    logger -t "${NAME}" "${INET}: not ready"
    sleep 2
  done

  echo ${PROC} ${ARGS}
  
  procd_open_instance
  procd_set_param command ${PROC} -s ${ARGS}
  procd_close_instance
}
